table DIM_MANAGERS
	lineageTag: 984b59d8-9262-4927-a407-42dc2beef2a9

	column 'Manager ID'
		dataType: string
		lineageTag: 8e04b227-247b-4aff-a8ad-377344c4a593
		summarizeBy: none
		sourceColumn: Manager ID

		annotation SummarizationSetBy = Automatic

	column 'Manager Name'
		dataType: string
		lineageTag: 2b304ee3-8386-4948-8458-9338efe85ad5
		summarizeBy: none
		sourceColumn: Manager Name

		annotation SummarizationSetBy = Automatic

	column 'First Name'
		dataType: string
		lineageTag: 420d59c2-a36a-4e0e-9d99-9bf69bc835d8
		summarizeBy: none
		sourceColumn: First Name

		annotation SummarizationSetBy = Automatic

	column 'Last Name'
		dataType: string
		lineageTag: fd0b9b23-f09a-4558-881c-26d04944f616
		summarizeBy: none
		sourceColumn: Last Name

		annotation SummarizationSetBy = Automatic

	column Territory
		dataType: string
		lineageTag: 7b08e2fd-225d-4f2e-abfb-7e7f037c1383
		summarizeBy: none
		sourceColumn: Territory

		annotation SummarizationSetBy = Automatic

	column 'Image URL'
		dataType: string
		lineageTag: b8473b1e-30e3-4e85-ae17-7a03dc15bcfd
		summarizeBy: none
		sourceColumn: Image URL

		annotation SummarizationSetBy = Automatic

	partition DIM_MANAGERS = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\user\Desktop\Power BI Courses\Modern UX-UI Power BI Report\Financial Sample.xlsx"), null, true),
				    DIM_MANAGERS_Table = Source{[Item="DIM_MANAGERS",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(DIM_MANAGERS_Table,{{"Manager ID", type text}, {"Manager Name", type text}, {"First Name", type text}, {"Last Name", type text}, {"Territory", type text}, {"Image URL", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

