table FACT_SALES
	lineageTag: 2a24266f-d403-4cb4-a804-16476c03a3e2

	column YearMonth
		dataType: string
		lineageTag: 13b9814a-ca5f-45ae-970b-5e6a73b0c0b1
		summarizeBy: none
		sourceColumn: YearMonth

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 35a603c3-af1e-460c-b55f-9c24388d9224
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: bf64b03e-8428-4a92-b45f-56b8f380fd4a
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 82ada99b-0e84-44a0-8de6-456face2a1a4
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Discount Band'
		dataType: string
		lineageTag: 100b0e0c-c8d8-4f38-baf8-952283194016
		summarizeBy: none
		sourceColumn: Discount Band

		annotation SummarizationSetBy = Automatic

	column 'Manager ID'
		dataType: string
		lineageTag: d83ff074-bcfe-467b-825c-0fe967e01016
		summarizeBy: none
		sourceColumn: Manager ID

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: int64
		formatString: 0
		lineageTag: 68d8ad31-f8c8-4d4f-83fa-da8fd6284f5e
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

	column 'Manufacturing Price'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 85a65fd1-f682-4edf-9c6a-13bbd03b19a6
		summarizeBy: sum
		sourceColumn: Manufacturing Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Sales Price'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: d967cf5f-2a82-4e09-9848-79ada460a6cd
		summarizeBy: sum
		sourceColumn: Sales Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Gross Sales'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: c8e847b1-79e3-4365-b899-774ef160896a
		summarizeBy: sum
		sourceColumn: Gross Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Discounts
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 0da06d4e-dd79-47db-bc9a-65c48d4aa9f1
		summarizeBy: sum
		sourceColumn: Discounts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Sales
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 832c3e71-ad95-459a-85ac-38cdb6b0ba86
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column COGs
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: c7c8948b-f6e1-4cbf-9817-f82e92d6f689
		summarizeBy: sum
		sourceColumn: COGs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Profit
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: bab10373-0a0a-4a4c-a89e-3291576393d3
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Discount Band ID'
		dataType: string
		lineageTag: 6e74ac27-9ebf-4ced-b152-8b52cca9dce3
		summarizeBy: none
		sourceColumn: Discount Band ID

		annotation SummarizationSetBy = Automatic

	column 'Product Bane (Short)'
		dataType: string
		lineageTag: 74605f9c-c5f8-444e-8784-97a710245f68
		summarizeBy: none
		sourceColumn: Product Bane (Short)

		annotation SummarizationSetBy = Automatic

	column 'Segment Short Name' =
			
			SWITCH(
			    [Segment],
			    "Government","Gov",
			    "Channel Partners", "CP",
			    "Enterprise", "Ent",
			    "Midmarket", "MM",
			    "Small Business", "Small Biz"
			     )
		lineageTag: d67b984c-5c1c-43d2-a0be-c530c4fe52ca
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Country Short Name' =
			
			SWITCH(
			    [Country],
			    "United States", "USA",
			    FACT_SALES[Country]
			     )
		lineageTag: a56763d2-bad0-4965-9922-920ebe1062bf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition FACT_SALES = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\user\Desktop\Power BI Courses\Modern UX-UI Power BI Report\Financial Sample.xlsx"), null, true),
				    FACT_SALES_Table = Source{[Item="FACT_SALES",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(FACT_SALES_Table,{{"Segment", type text}, {"Country", type text}, {"Product", type text}, {"Discount Band", type text}, {"Units Sold", Int64.Type}, {"Manufacturing Price", Int64.Type}, {"Sale Price", Int64.Type}, {"Gross Sales", type number}, {"Discounts", type number}, {" Sales", type number}, {"COGS", type number}, {"Profit", type number}, {"Date", type date}, {"Month Number", Int64.Type}, {"Month Name", type text}, {"Year", Int64.Type}, {"Manager ID", type text}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Custom", each Number.ToText([Month Number],"00")),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom",{{"Gross Sales", Int64.Type}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type3", "YearMonth", each Number.ToText([Year],"0000")&[Custom]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom1",{{"YearMonth", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"Custom", "Date", "Month Number", "Month Name", "Year"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns",{"YearMonth", "Segment", "Country", "Product", "Discount Band", "Units Sold", "Manufacturing Price", "Sale Price", "Gross Sales", "Discounts", " Sales", "COGS", "Profit", "Manager ID"}),
				    #"Grouped Rows" = Table.Group(#"Reordered Columns", {"YearMonth", "Segment", "Country", "Product", "Discount Band", "Manager ID"}, {{"Units Sold", each List.Sum([Units Sold]), type nullable number}, {"Manufacturing Price", each List.Average([Manufacturing Price]), type nullable number}, {"Sales Price", each List.Average([Sale Price]), type nullable number}, {"Gross Sales", each List.Average([Gross Sales]), type nullable number}, {"Discounts", each List.Sum([Discounts]), type nullable number}, {"Sales", each List.Sum([#" Sales"]), type nullable number}, {"COGs", each List.Sum([COGS]), type nullable number}, {"Profit", each List.Sum([Profit]), type nullable number}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Grouped Rows",{{"Units Sold", Int64.Type}, {"Manufacturing Price", Currency.Type}, {"Sales Price", Currency.Type}, {"Gross Sales", Currency.Type}, {"Discounts", Currency.Type}, {"Sales", Currency.Type}, {"COGs", Currency.Type}, {"Profit", Currency.Type}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type2","United States of America","United States",Replacer.ReplaceText,{"Country"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Replaced Value", "Discount Band ID", each if Text.Contains([Discount Band], "High") then 1 else if Text.Contains([Discount Band], "Medium") then 2 else if Text.Contains([Discount Band], "Low") then 3 else if Text.Contains([Discount Band], "None") then 4 else 0),
				    #"Inserted First Characters" = Table.AddColumn(#"Added Conditional Column", "First Characters", each Text.Start([Product], 5), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted First Characters",{{"First Characters", "Product Bane (Short)"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

